In [1]:
import numpy as np

# An exemplar array 
arr = np.array([[-1, 2, 0, 4], 
                [4, -0.5, 6, 0], 
                [2.6, 0, 7, 8], 
                [3, -7, 4, 2.0]]) 


In [2]:
# Slicing array 
temp = arr[:2, ::2] 
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp) 


Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [3]:
temp = arr[:2, ::] 
print (temp) 

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]]


In [4]:
temp = arr[:2, :] 
print (temp) 

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]]


In [5]:
temp = arr[:2, :3] 
print (temp) 

[[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [6]:
temp = arr[:2, ::1] 
print (temp) 

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]]


In [7]:
temp = arr[:2, ::3] 
print (temp) 

[[-1.  4.]
 [ 4.  0.]]


In [8]:
temp = arr[:, ::3] 
print (temp) 

[[-1.   4. ]
 [ 4.   0. ]
 [ 2.6  8. ]
 [ 3.   2. ]]


In [9]:
cond = arr > 0 
temp = arr[cond] 
print ("\nElements greater than 0:\n", temp)


Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [14]:
# Integer array indexing example 
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]] 
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp) 


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]


In [11]:
print(arr)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [15]:
# You may wish to square the multiples of 2  
cond= arr%2==0
print(arr[cond]**2) 

[ 4.  0. 16. 16. 36.  0.  0. 64. 16.  4.]


In [19]:
# Create a sequence of integers from 10 to 1 with a step of -2 
a = np.arange(10, 1, -2)  
print("\n A sequential array with a negative step: \n",a) 
 
newarr = a[[3, 1, 2 ]] 
print("\n Elements at these indices are:\n",newarr) 


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [20]:
# Slicing (start,stop,step)

# Arrange elements from 0 to 19 
a = np.arange(20) 
print("\n Array is:\n ",a) 
  
# a[start:stop:step] 
print("\n a[-8:17:1]  = ",a[-8:17:1])  
  
# The : operator means all elements till the end. 
print("\n a[10:]  = ",a[10:]) 


 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1]  =  [12 13 14 15 16]

 a[10:]  =  [10 11 12 13 14 15 16 17 18 19]


In [21]:
a = np.array([1, 2, 5, 3]) 
  
# add 1 to every element 
print ("Adding 1 to every element:", a+1) 
  
# subtract 3 from each element 
print ("Subtracting 3 from each element:", a-3) 
  
# multiply each element by 10 
print ("Multiplying each element by 10:", a*10) 
  
# square each element 
print ("Squaring each element:", a**2) 
  
# modify existing array 
a *= 2
print ("Doubled each element of original array:", a) 
  
# transpose of array 
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]]) 
  
print ("\nOriginal array:\n", a) 
print ("Transpose of array:\n", a.T) 

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [28]:
# maximum element of array 
print ("Largest element is:", a.max()) 

#axis 0 is column and axis 1 is row
print ("Row-wise maximum elements:", 
                    a.max(axis = 1)) 
  
# minimum element of array 
print ("Column-wise minimum elements:", 
                        a.min(axis = 0))  
  
# sum of array elements 
print ("Sum of all array elements:", 
                            a.sum()) 
print ("Sum as per row wise elements:", 
                            a.sum(axis=1)) 
# cumulative sum along each row 
print ("Cumulative sum along each row:\n", 
                        a.cumsum(axis = 1)) 

Largest element is: 9
Row-wise maximum elements: [3 5 9]
Column-wise minimum elements: [1 2 0]
Sum of all array elements: 33
Sum as per row wise elements: [ 6 12 15]
Cumulative sum along each row:
 [[ 1  3  6]
 [ 3  7 12]
 [ 9 15 15]]


In [29]:

  
a = np.array([[1, 3, 5, 7, 9, 11], 
              [2, 4, 6, 8, 10, 12]]) 
  
# horizontal splitting 
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2)) 
  
# vertical splitting 
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(a, 2))

Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]

Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [30]:

# Python program to demonstrate 
# binary operators in Numpy 
import numpy as np 
  
a = np.array([[1, 2], 
            [3, 4]]) 
b = np.array([[4, 3], 
            [2, 1]]) 
  
# add arrays 
print ("Array sum:\n", a + b) 
  
# multiply arrays (elementwise multiplication) 
print ("Array multiplication:\n", a*b) 
  
# matrix multiplication 
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [31]:
# Python program to demonstrate 
# universal functions in numpy 
import numpy as np 
  
# create an array of sine values 
a = np.array([0, np.pi/2, np.pi]) 
print ("Sine values of array elements:", np.sin(a)) 
  
# exponential values 
a = np.array([0, 1, 2, 3]) 
print ("Exponent of array elements:", np.exp(a)) 
  
# square root of array values 
print ("Square root of array elements:", np.sqrt(a)) 

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]
